# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fd6bfd4425f9f1dcc83a1799a210cc496cdb69554c025a13d692696bd3395d31fb228d03352aff6d5648b16c9e9ea8bcdde07f392c5b5f98b5c6601e8442384b

test:
  secret_key_base: b1f166d5c0b2abdd2237fc80d37a60991583aa0a7acbc394d03b7598cf93cf079652149b82da4114d5f900e48e9239b8f4dd25d02e47849973f7f75a6a950d92

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
